INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AF', 'COUNTRY', 'Afghanistan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AL', 'COUNTRY', 'Albania');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DZ', 'COUNTRY', 'Algeria');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DS', 'COUNTRY', 'American Samoa');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AD', 'COUNTRY', 'Andorra');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AO', 'COUNTRY', 'Angola');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AI', 'COUNTRY', 'Anguilla');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AQ', 'COUNTRY', 'Antarctica');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AG', 'COUNTRY', 'Antigua and Barbuda');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AR', 'COUNTRY', 'Argentina');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AM', 'COUNTRY', 'Armenia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AW', 'COUNTRY', 'Aruba');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AU', 'COUNTRY', 'Australia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AT', 'COUNTRY', 'Austria');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AZ', 'COUNTRY', 'Azerbaijan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BS', 'COUNTRY', 'Bahamas');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BH', 'COUNTRY', 'Bahrain');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BD', 'COUNTRY', 'Bangladesh');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BB', 'COUNTRY', 'Barbados');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BY', 'COUNTRY', 'Belarus');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BE', 'COUNTRY', 'Belgium');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BZ', 'COUNTRY', 'Belize');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BJ', 'COUNTRY', 'Benin');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BM', 'COUNTRY', 'Bermuda');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BT', 'COUNTRY', 'Bhutan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BO', 'COUNTRY', 'Bolivia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BA', 'COUNTRY', 'Bosnia and Herzegovina');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BW', 'COUNTRY', 'Botswana');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BV', 'COUNTRY', 'Bouvet Island');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BR', 'COUNTRY', 'Brazil');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IO', 'COUNTRY', 'British Indian Ocean Territory');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BN', 'COUNTRY', 'Brunei Darussalam');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BG', 'COUNTRY', 'Bulgaria');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BF', 'COUNTRY', 'Burkina Faso');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'BI', 'COUNTRY', 'Burundi');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KH', 'COUNTRY', 'Cambodia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CM', 'COUNTRY', 'Cameroon');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CA', 'COUNTRY', 'Canada');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CV', 'COUNTRY', 'Cape Verde');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KY', 'COUNTRY', 'Cayman Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CF', 'COUNTRY', 'Central African Republic');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TD', 'COUNTRY', 'Chad');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CL', 'COUNTRY', 'Chile');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CN', 'COUNTRY', 'China');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CX', 'COUNTRY', 'Christmas Island');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CC', 'COUNTRY', 'Cocos (Keeling) Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CO', 'COUNTRY', 'Colombia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KM', 'COUNTRY', 'Comoros');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CG', 'COUNTRY', 'Congo');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CK', 'COUNTRY', 'Cook Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CR', 'COUNTRY', 'Costa Rica');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'HR', 'COUNTRY', 'Croatia (Hrvatska)');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CU', 'COUNTRY', 'Cuba');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CY', 'COUNTRY', 'Cyprus');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CZ', 'COUNTRY', 'Czech Republic');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DK', 'COUNTRY', 'Denmark');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DJ', 'COUNTRY', 'Djibouti');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DM', 'COUNTRY', 'Dominica');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DO', 'COUNTRY', 'Dominican Republic');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TP', 'COUNTRY', 'East Timor');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'EC', 'COUNTRY', 'Ecuador');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'EG', 'COUNTRY', 'Egypt');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SV', 'COUNTRY', 'El Salvador');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GQ', 'COUNTRY', 'Equatorial Guinea');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ER', 'COUNTRY', 'Eritrea');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'EE', 'COUNTRY', 'Estonia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ET', 'COUNTRY', 'Ethiopia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FK', 'COUNTRY', 'Falkland Islands (Malvinas)');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FO', 'COUNTRY', 'Faroe Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FJ', 'COUNTRY', 'Fiji');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FI', 'COUNTRY', 'Finland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FR', 'COUNTRY', 'France');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FX', 'COUNTRY', 'France, Metropolitan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GF', 'COUNTRY', 'French Guiana');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PF', 'COUNTRY', 'French Polynesia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TF', 'COUNTRY', 'French Southern Territories');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GA', 'COUNTRY', 'Gabon');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GM', 'COUNTRY', 'Gambia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GE', 'COUNTRY', 'Georgia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'DE', 'COUNTRY', 'Germany');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GH', 'COUNTRY', 'Ghana');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GI', 'COUNTRY', 'Gibraltar');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GK', 'COUNTRY', 'Guernsey');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GR', 'COUNTRY', 'Greece');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GL', 'COUNTRY', 'Greenland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GD', 'COUNTRY', 'Grenada');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GP', 'COUNTRY', 'Guadeloupe');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GU', 'COUNTRY', 'Guam');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GT', 'COUNTRY', 'Guatemala');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GN', 'COUNTRY', 'Guinea');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GW', 'COUNTRY', 'Guinea-Bissau');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GY', 'COUNTRY', 'Guyana');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'HT', 'COUNTRY', 'Haiti');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'HM', 'COUNTRY', 'Heard and Mc Donald Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'HN', 'COUNTRY', 'Honduras');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'HK', 'COUNTRY', 'Hong Kong');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'HU', 'COUNTRY', 'Hungary');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IS', 'COUNTRY', 'Iceland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IN', 'COUNTRY', 'India');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IM', 'COUNTRY', 'Isle of Man');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ID', 'COUNTRY', 'Indonesia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IR', 'COUNTRY', 'Iran (Islamic Republic of)');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IQ', 'COUNTRY', 'Iraq');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IE', 'COUNTRY', 'Ireland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IL', 'COUNTRY', 'Israel');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'IT', 'COUNTRY', 'Italy');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CI', 'COUNTRY', 'Ivory Coast');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'JE', 'COUNTRY', 'Jersey');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'JM', 'COUNTRY', 'Jamaica');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'JP', 'COUNTRY', 'Japan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'JO', 'COUNTRY', 'Jordan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KZ', 'COUNTRY', 'Kazakhstan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KE', 'COUNTRY', 'Kenya');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KI', 'COUNTRY', 'Kiribati');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KP', 'COUNTRY', 'Korea, Democratic People''s Republic of');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KR', 'COUNTRY', 'Korea, Republic of');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'XK', 'COUNTRY', 'Kosovo');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KW', 'COUNTRY', 'Kuwait');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KG', 'COUNTRY', 'Kyrgyzstan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LA', 'COUNTRY', 'Lao People''s Democratic Republic');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LV', 'COUNTRY', 'Latvia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LB', 'COUNTRY', 'Lebanon');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LS', 'COUNTRY', 'Lesotho');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LR', 'COUNTRY', 'Liberia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LY', 'COUNTRY', 'Libyan Arab Jamahiriya');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LI', 'COUNTRY', 'Liechtenstein');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LT', 'COUNTRY', 'Lithuania');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LU', 'COUNTRY', 'Luxembourg');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MO', 'COUNTRY', 'Macau');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MK', 'COUNTRY', 'Macedonia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MG', 'COUNTRY', 'Madagascar');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MW', 'COUNTRY', 'Malawi');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MY', 'COUNTRY', 'Malaysia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MV', 'COUNTRY', 'Maldives');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ML', 'COUNTRY', 'Mali');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MT', 'COUNTRY', 'Malta');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MH', 'COUNTRY', 'Marshall Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MQ', 'COUNTRY', 'Martinique');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MR', 'COUNTRY', 'Mauritania');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MU', 'COUNTRY', 'Mauritius');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TY', 'COUNTRY', 'Mayotte');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MX', 'COUNTRY', 'Mexico');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'FM', 'COUNTRY', 'Micronesia, Federated States of');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MD', 'COUNTRY', 'Moldova, Republic of');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MC', 'COUNTRY', 'Monaco');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MN', 'COUNTRY', 'Mongolia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ME', 'COUNTRY', 'Montenegro');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MS', 'COUNTRY', 'Montserrat');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MA', 'COUNTRY', 'Morocco');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MZ', 'COUNTRY', 'Mozambique');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MM', 'COUNTRY', 'Myanmar');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NA', 'COUNTRY', 'Namibia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NR', 'COUNTRY', 'Nauru');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NP', 'COUNTRY', 'Nepal');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NL', 'COUNTRY', 'Netherlands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AN', 'COUNTRY', 'Netherlands Antilles');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NC', 'COUNTRY', 'New Caledonia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NZ', 'COUNTRY', 'New Zealand');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NI', 'COUNTRY', 'Nicaragua');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NE', 'COUNTRY', 'Niger');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NG', 'COUNTRY', 'Nigeria');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NU', 'COUNTRY', 'Niue');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NF', 'COUNTRY', 'Norfolk Island');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'MP', 'COUNTRY', 'Northern Mariana Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'NO', 'COUNTRY', 'Norway');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'OM', 'COUNTRY', 'Oman');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PK', 'COUNTRY', 'Pakistan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PW', 'COUNTRY', 'Palau');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PS', 'COUNTRY', 'Palestine');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PA', 'COUNTRY', 'Panama');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PG', 'COUNTRY', 'Papua New Guinea');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PY', 'COUNTRY', 'Paraguay');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PE', 'COUNTRY', 'Peru');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PH', 'COUNTRY', 'Philippines');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PN', 'COUNTRY', 'Pitcairn');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PL', 'COUNTRY', 'Poland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PT', 'COUNTRY', 'Portugal');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PR', 'COUNTRY', 'Puerto Rico');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'QA', 'COUNTRY', 'Qatar');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'RE', 'COUNTRY', 'Reunion');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'RO', 'COUNTRY', 'Romania');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'RU', 'COUNTRY', 'Russian Federation');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'RW', 'COUNTRY', 'Rwanda');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'KN', 'COUNTRY', 'Saint Kitts and Nevis');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LC', 'COUNTRY', 'Saint Lucia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VC', 'COUNTRY', 'Saint Vincent and the Grenadines');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'WS', 'COUNTRY', 'Samoa');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SM', 'COUNTRY', 'San Marino');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ST', 'COUNTRY', 'Sao Tome and Principe');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SA', 'COUNTRY', 'Saudi Arabia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SN', 'COUNTRY', 'Senegal');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'RS', 'COUNTRY', 'Serbia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SC', 'COUNTRY', 'Seychelles');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SL', 'COUNTRY', 'Sierra Leone');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SG', 'COUNTRY', 'Singapore');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SK', 'COUNTRY', 'Slovakia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SI', 'COUNTRY', 'Slovenia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SB', 'COUNTRY', 'Solomon Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SO', 'COUNTRY', 'Somalia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ZA', 'COUNTRY', 'South Africa');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GS', 'COUNTRY', 'South Georgia South Sandwich Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SS', 'COUNTRY', 'South Sudan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ES', 'COUNTRY', 'Spain');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'LK', 'COUNTRY', 'Sri Lanka');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SH', 'COUNTRY', 'St. Helena');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'PM', 'COUNTRY', 'St. Pierre and Miquelon');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SD', 'COUNTRY', 'Sudan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SR', 'COUNTRY', 'Suriname');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SJ', 'COUNTRY', 'Svalbard and Jan Mayen Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SZ', 'COUNTRY', 'Swaziland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SE', 'COUNTRY', 'Sweden');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'CH', 'COUNTRY', 'Switzerland');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'SY', 'COUNTRY', 'Syrian Arab Republic');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TW', 'COUNTRY', 'Taiwan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TJ', 'COUNTRY', 'Tajikistan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TZ', 'COUNTRY', 'Tanzania, United Republic of');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TH', 'COUNTRY', 'Thailand');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TG', 'COUNTRY', 'Togo');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TK', 'COUNTRY', 'Tokelau');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TO', 'COUNTRY', 'Tonga');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TT', 'COUNTRY', 'Trinidad and Tobago');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TN', 'COUNTRY', 'Tunisia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TR', 'COUNTRY', 'Turkey');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TM', 'COUNTRY', 'Turkmenistan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TC', 'COUNTRY', 'Turks and Caicos Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'TV', 'COUNTRY', 'Tuvalu');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'UG', 'COUNTRY', 'Uganda');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'UA', 'COUNTRY', 'Ukraine');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'AE', 'COUNTRY', 'United Arab Emirates');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'GB', 'COUNTRY', 'United Kingdom');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'US', 'COUNTRY', 'United States');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'UM', 'COUNTRY', 'United States minor outlying islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'UY', 'COUNTRY', 'Uruguay');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'UZ', 'COUNTRY', 'Uzbekistan');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VU', 'COUNTRY', 'Vanuatu');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VA', 'COUNTRY', 'Vatican City State');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VE', 'COUNTRY', 'Venezuela');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VN', 'COUNTRY', 'Vietnam');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VG', 'COUNTRY', 'Virgin Islands (British)');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'VI', 'COUNTRY', 'Virgin Islands (U.S.)');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'WF', 'COUNTRY', 'Wallis and Futuna Islands');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'EH', 'COUNTRY', 'Western Sahara');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'YE', 'COUNTRY', 'Yemen');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ZR', 'COUNTRY', 'Zaire');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ZM', 'COUNTRY', 'Zambia');
INSERT INTO `Dictionary` (active,dicKey,type,value) VALUES (1, 'ZW', 'COUNTRY', 'Zimbabwe');